### ISSUE TITLE
Add support to processors

### ISSUE THREAD

**Issue by kriansa** [gilbarbara/codeclimate-stylelint#14]
I'd love to have support to processors listed on https://stylelint.io/user-guide/processors/

How can we implement that? Is it just a new entry on `package.json`?

**Comment by KrisOlszewski** [comment]
This would be great. Especially for [stylelint-processor-html](https://github.com/ccbikai/stylelint-processor-html) and [stylelint-processor-arbitrary-tags](https://github.com/mapbox/stylelint-processor-arbitrary-tags) in order to lint VueJS files.
