### ISSUE TITLE
Add support for stylelint-config-css-modules

### ISSUE THREAD

**Issue by killthrush** [gilbarbara/codeclimate-stylelint#16]
Hi!  Our team has an avid interest in using [CSS Modules](https://github.com/css-modules/css-modules) with CodeClimate.  We've had a lot of success writing application code with them and have recently configured stylelint to help us keep things clean.  Our config includes the use of the [stylelint-config-css-modules](https://github.com/pascalduez/stylelint-config-css-modules) shared ruleset, which is not included in the docker image.

I'm going to see if I can put together a quick PR with some tests to implement this change.  Hopefully we can get a new image soon.

Thanks!

**Comment by gilbarbara** [comment]
Great, I was thinking about adding it

**Comment by killthrush** [comment]
Addressed in https://github.com/gilbarbara/codeclimate-stylelint/pull/17

**Comment by killthrush** [comment]
@gilbarbara - just a friendly bump... do you have the bandwidth to look at this PR?

**Comment by gilbarbara** [comment]
Sorry!
I'll do it tonight! 😄

**Comment by gilbarbara** [comment]
hey

I've merged #17 but still have some updates to do before publishing a new version to the codeclimate docker image. 80% done!

**Comment by killthrush** [comment]
Thanks @gilbarbara - your master branch looks good on my end.  Feel free to close this issue when you release!

**Comment by gilbarbara** [comment]
Released as [1.7.0](https://github.com/gilbarbara/codeclimate-stylelint/releases/tag/v1.7.0)
I've already sent notice to codeclimate about the release and it should be on their site soon.

Thanks @killthrush
