### ISSUE TITLE
Rule selector-max-pseudo-class missing

### ISSUE THREAD

**Issue by Gwerlas** [gilbarbara/codeclimate-stylelint#20]
Hello,

When I launch codeclimate on my code, I have this error :
```
Error: Undefined rule selector-max-pseudo-class
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.
```

Is it possible to rebuild the docker image with the current stylelint version ?

**Comment by gilbarbara** [comment]
Updated > 08310a613d98bc127ed462f5bf301b6928987611
