### ISSUE TITLE
Support for styled-components

### ISSUE THREAD

**Issue by dpuscher** [gilbarbara/codeclimate-stylelint#25]
[`styled-components`](https://github.com/styled-components/styled-components) is a popular css-in-js library and `stylelint` is the tool of choice to do linting of the css parts.

The official documentation has detailed instructions on how to setup linting. For CodeClimate to work with it, we need to add support for the following packages:

**Processors:**
- `stylelint-processor-styled-components`

**Configs:**
- `stylelint-config-styled-components`
- `stylelint-config-recommended`

Documentation:
https://www.styled-components.com/docs/tooling#stylelint

**Comment by gilbarbara** [comment]
Hey,

I will take a look at this when I have some spare time.
Feel free to submit a PR.

**Comment by gilbarbara** [comment]
Added in 2.2.0
