### ISSUE TITLE
Error: Could not find "stylelint-config-styled-components". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by knightbk** [gilbarbara/codeclimate-stylelint#35]
I created an open source repo to demonstrate this failure, but how can we get support for `styled-components? 

Here is a link to the repo: 
https://github.com/knightbk/styled-components-test

And here is a link to the codeclimate error message:
https://codeclimate.com/github/knightbk/styled-components-test/builds/5

**Comment by andrewkatz** [comment]
This seems like not just an issue for styled components, but all of the "included" Stylelint config dependencies in this project. We're running into the same issue for the Stylelint Prettier plugin.

**Comment by ramon-villain** [comment]
@knightbk did you try to install "stylelint-processor-styled-components" and set it as a preprocessor on your `.stylelint.rc` file? I managed to get it working locally doings this trick. :)

**Comment by jfairley** [comment]
Ditto for me with `"stylelint-config-concentric-order"`.

```
Error: Could not find "stylelint-config-concentric-order". Do you need a `configBasedir`?
```

**Comment by bmulholland** [comment]
@gilbarbara I'd be happy to do a timeboxed attempt at this. Do you have any insights or educated guesses to get me started?

**Comment by gilbarbara** [comment]
Hey @bmulholland 

I'd start with codeclimate engine documentation but basically, the code is analyzed statically against the engine, so the dependencies need to be configured in it.

Anyway, I've updated the dependencies.

Thanks

**Comment by gilbarbara** [comment]
@knightbk @andrewkatz 

Codeclimate is running an older version of this engine that doesn't include these packages. They need to update it.

I've updated the dependencies in 2.3.0 (engine 13.7.2)

**Comment by gilbarbara** [comment]
@jfairley Added in 2.3.0

**Comment by bmulholland** [comment]
@gilbarbara Awesome, thank you! I've pinged CodeClimate to update their version, which hopefully they can do soon.

**Comment by efueger** [comment]
Hi @bmulholland - we've updated Code Climate's version to use these dependencies. Thanks for the nudge!

Cheers,
Emily
