### ISSUE TITLE
Request: support the `stylelint-config-sugarss-recommended` depdendency

### ISSUE THREAD

**Issue by davehenton** [gilbarbara/codeclimate-stylelint#37]
Dave here from Code Climate. We've had a customer request support for the `stylelint-config-sugarss-recommended` in the next engine update. Leaving this here for visibility.

**Comment by gilbarbara** [comment]
Hey @davehenton 
Is CodeClimate running the latest version (9.10.1) of this engine?
If this [page](https://docs.codeclimate.com/docs/stylelint) is accurate, it isn't.

**Comment by davehenton** [comment]
Hey @gilbarbara, Code Climate is actually running version 9.9.0. I've updated our docs to reflect the current version.

Specifically, we're using [this commit](https://github.com/gilbarbara/codeclimate-stylelint/commit/7f3dd3c482cdecf784e797598e8f9c8aefcd4de7).

**Comment by gilbarbara** [comment]
hey @davehenton 

I've added it in 2.3.0 (engine 13.7.2). You'll need to update the engine.
