### ISSUE TITLE
Upgrade stylelint version to support the new rule names

### ISSUE THREAD

**Issue by miktirr** [gilbarbara/codeclimate-stylelint#44]
As per requested by the support of Code Climate, here is a separate issue regarding errors with the latest version of stylelint.

If one updates to the latest stylelint version (13.7.x) and to the new configuration practices, this engine throws the following error:

```
•• Timing: .engineConfig: 0.01s
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Error: Undefined rule declaration-property-value-disallowed-list
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.
```

This is because stylelint has deprecated `*-blacklist`, `*-requirelist` and `*-whitelist` rules in favor of the new `*-disallowed-list`, `*-required-list` and `*-allowed-list` ones in [the version 13.70](https://github.com/stylelint/stylelint/releases/tag/13.7.0) ([see more](https://github.com/stylelint/stylelint/pull/4845)), and codeclimate-stylelint engine still uses the version 9.10.1.

Relates to https://github.com/gilbarbara/codeclimate-stylelint/issues/40

**Comment by gilbarbara** [comment]
Feel free to submit a PR.

**Comment by gilbarbara** [comment]
Updated in 2.3.0 (engine 13.7.2)

**Comment by efueger** [comment]
Updated Code Climate to use @gilbarbara 's latest commits. 👍
