### ISSUE TITLE
Add a linter plugin for Twig

### ISSUE THREAD

**Issue by MPParsley** [gilbarbara/codeclimate-stylelint#46]
[Twigcs](https://github.com/friendsoftwig/twigcs) aims to be for twig what phpcs is to php. It checks your codebase for violations on coding standards in Twig files.

Note: this may not be the proper repository to report this as it may require a [new code climate engine](https://github.com/codeclimate/codeclimate/issues/1003). Please move or close this issue as needed.

**Comment by gilbarbara** [comment]
This is definitely not the place for this issue as this engine is for the stylelint and not related to PHP at all.

**Comment by MPParsley** [comment]
Hi @gilbarbara, this issue is about Twig, not PHP, but indeed twig is not a "style" language.

FYI, I came here because of [this comment](https://github.com/codeclimate/codeclimate/issues/633#issuecomment-299525982):

> However, there's a workaround. Many engines come packaged with relevant plugins already installed. You can go ahead and open an issue or PR on the **stylelint project** to add the dependency you'd like to use.
